---
#  Copyright (c) 2019 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA Records Ansible is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA Records Ansible is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA Records Ansible. If not, see <http://www.gnu.org/licenses/>.

- name: Install gunicorn
  pip:
    name: gunicorn
    state: present
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    virtualenv_command: /usr/bin/python3 -m venv

- when: ansible_os_family == "RedHat"
  block:
    - name: Transfer gunicorn selinux type enforcement file
      copy:
        src: ara-gunicorn.te
        dest: "{{ ara_api_root_dir }}/ara-gunicorn.te"

    # TODO: Only compile a new module and policy package when necessary
    - name: Compile ara-gunicorn selinux module
      command: "checkmodule -M -m -o {{ ara_api_root_dir }}/ara-gunicorn.mod {{ ara_api_root_dir }}/ara-gunicorn.te"

    - name: Compile ara-gunicorn selinux policy package
      command: "semodule_package -o {{ ara_api_root_dir }}/ara-gunicorn.pp -m {{ ara_api_root_dir }}/ara-gunicorn.mod"

- become: yes
  block:
    # TODO: Only install the selinux module if it has changed
    - name: Install selinux policy package
      command: "semodule -i {{ ara_api_root_dir }}/ara-gunicorn.pp"
      when: ansible_os_family == "RedHat"

    - name: Set up systemd unit file for gunicorn to run the ARA API
      template:
        src: ara-api.service.j2
        dest: /etc/systemd/system/ara-api.service
        owner: root
        group: root
        mode: 0644
      notify:
        - restart ara-api

    - name: Enable and start ara-api with gunicorn
      service:
        name: ara-api
        state: started
        enabled: yes
        daemon_reload: yes
      register: ara_api_service_enabled
